// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/api. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds every type the HTTP API returns. Nothing else is exposed to
tygo, and every field carries an explicit camelCase JSON tag.
*/

/**
 * ErrorResponse is the single error envelope used by every endpoint.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * ErrorBody carries a machine code, a human message and an optional
 * machine-readable detail.
 */
export interface ErrorBody {
  code: string;
  message: string;
  /**
   * ActivityID is set on duplicate_activity responses so the upload UI can
   * link to the activity that already exists.
   */
  activityId?: number /* int64 */;
}
/**
 * Me is the authenticated user's own profile.
 */
export interface Me {
  id: number /* int64 */;
  username: string;
  email: string;
  displayName: string;
  bio: string;
  avatarUrl: string;
  emailVerified: boolean;
  isAdmin: boolean;
  profileVisibility: string;
  activitiesVisibility: string;
  followPolicy: string;
  mentionPolicy: string;
  trimScope: string;
  trimRadiusM: number /* int64 */;
  createdAt: string;
}
/**
 * UserProfile is another user's public profile. FollowState is one of
 * none | following | pending_outgoing | pending_incoming | self.
 */
export interface UserProfile {
  id: number /* int64 */;
  username: string;
  displayName: string;
  bio: string;
  avatarUrl: string;
  followerCount: number /* int64 */;
  followingCount: number /* int64 */;
  activityCount: number /* int64 */;
  followState: string;
  isMe: boolean;
  isPrivate: boolean;
}
/**
 * UserRef is a compact user reference used in lists and notifications.
 */
export interface UserRef {
  username: string;
  displayName: string;
  avatarUrl: string;
}
/**
 * Photo is one stored image variant pair.
 */
export interface Photo {
  id: number /* int64 */;
  url: string;
  thumbUrl: string;
  width: number /* int32 */;
  height: number /* int32 */;
}
/**
 * Comment is one activity comment.
 */
export interface Comment {
  id: number /* int64 */;
  username: string;
  displayName: string;
  avatarUrl: string;
  body: string;
  mentions: string[];
  createdAt: string;
  canDelete: boolean;
}
/**
 * CommentCreated is the POST /comments response.
 */
export interface CommentCreated {
  comment: Comment;
  droppedMentions: string[];
}
/**
 * Notification is one in-app notification.
 */
export interface Notification {
  id: number /* int64 */;
  kind: string;
  actor: UserRef;
  activityId?: number /* int64 */;
  commentId?: number /* int64 */;
  createdAt: string;
  readAt?: string;
}
/**
 * NotificationCount is the unread badge payload.
 */
export interface NotificationCount {
  unread: number /* int64 */;
}
/**
 * ProviderInfo reports one OAuth provider's availability.
 */
export interface ProviderInfo {
  id: string;
  enabled: boolean;
}
/**
 * LinkedIdentity is one OAuth provider linked to the current account.
 */
export interface LinkedIdentity {
  provider: string;
  email?: string;
  createdAt: string;
}
/**
 * ConfigResponse is the public boot configuration.
 */
export interface ConfigResponse {
  registrationOpen: boolean;
  providers: ProviderInfo[];
  pmtilesUrl?: string;
  tilesAttribution: string;
  version: string;
  /**
   * IntervalsOAuth and Strava tell the settings page which connect buttons
   * this instance can actually offer.
   */
  intervalsOAuth: boolean;
  strava: boolean;
  webhooks: boolean;
}
/**
 * SportTotals aggregates one sport over a date range.
 */
export interface SportTotals {
  sport: string;
  count: number /* int64 */;
  distanceM: number /* float64 */;
  elevationGainM: number /* float64 */;
  movingTimeS: number /* int64 */;
  elapsedTimeS: number /* int64 */;
}
/**
 * StatsResponse is the per-sport statistics payload.
 */
export interface StatsResponse {
  sports: SportTotals[];
  all: SportTotals;
}
/**
 * ActivityPage is one page-numbered activity list. Page is 1-based, clamped to
 * [1, TotalPages] (or 1 when there are no rows); PageSize is the effective
 * ?limit=; TotalPages is 0 when there are no rows.
 */
export interface ActivityPage {
  items: ActivitySummary[];
  page: number /* int64 */;
  pageSize: number /* int64 */;
  total: number /* int64 */;
  totalPages: number /* int64 */;
}
/**
 * CommentPage is one keyset-paginated comment list.
 */
export interface CommentPage {
  items: Comment[];
  nextBefore?: number /* int64 */;
}
/**
 * NotificationPage is one keyset-paginated notification list.
 */
export interface NotificationPage {
  items: Notification[];
  nextBefore?: number /* int64 */;
}
/**
 * UserPage is one keyset-paginated user list.
 */
export interface UserPage {
  items: UserRef[];
  nextBefore?: number /* int64 */;
}
/**
 * FollowResult is the follow/unfollow endpoint payload.
 */
export interface FollowResult {
  followState: string;
  followerCount: number /* int64 */;
}
/**
 * LikeResult is the like endpoint payload.
 */
export interface LikeResult {
  likeCount: number /* int64 */;
  likedByMe: boolean;
}
/**
 * ActivitySummary is one row of any activity list.
 */
export interface ActivitySummary {
  id: number /* int64 */;
  userId: number /* int64 */;
  username: string;
  displayName: string;
  /**
   * AvatarURL is the owner's avatar thumbnail; empty when they have none.
   */
  avatarUrl: string;
  title: string;
  sport: string;
  startedAt: string;
  distanceM: number /* float64 */;
  movingTimeS: number /* int64 */;
  elapsedTimeS: number /* int64 */;
  elevationGainM: number /* float64 */;
  avgSpeedMps?: number /* float64 */;
  maxSpeedMps?: number /* float64 */;
  avgHeartRate?: number /* int64 */;
  maxHeartRate?: number /* int64 */;
  avgCadence?: number /* float64 */;
  avgPowerW?: number /* float64 */;
  likeCount: number /* int64 */;
  commentCount: number /* int64 */;
  likedByMe: boolean;
  photoCount: number /* int64 */;
  visibility: string;
  /**
   * HasGps and RouteHidden are the owner's inputs: the client needs them to
   * render the "show route" switch, which MapAvailable alone cannot express
   * (an indoor activity has no route to hide but is not hidden either).
   */
  hasGps: boolean;
  routeHidden: boolean;
  /**
   * Track is a flattened [lat,lon,lat,lon,…] list with 5 decimal places,
   * already decimated to <=200 points and privacy-trimmed. Empty when the
   * activity has no drawable route.
   */
  track: number /* float64 */[];
  mapAvailable: boolean;
  /**
   * Photos is the first four photos by position, so feed cards can show a strip.
   */
  photos: Photo[];
  /**
   * Description is populated in list responses too, so the feed can render it.
   */
  description: string;
}
/**
 * ActivityDetail is the single-activity payload.
 */
export interface ActivityDetail extends ActivitySummary {
  canEdit: boolean;
  /**
   * Route is the untrimmed-but-decimated coordinate list for the map page,
   * subject to the same privacy rules as Track.
   */
  route: number /* float64 */[];
  streams: ActivityStreams;
}
/**
 * ActivityStreams are the charted series, decimated to <=600 values each.
 */
export interface ActivityStreams {
  elapsedS: number /* int64 */[];
  hr: (number /* int64 */ | undefined)[];
  cadence: (number /* int64 */ | undefined)[];
  power: (number /* int64 */ | undefined)[];
  speedMps: (number /* float64 */ | undefined)[];
  elevationM: (number /* float64 */ | undefined)[];
}
/**
 * Connection is one configured provider connection.
 */
export interface Connection {
  kind: string;
  athleteId?: string;
  autoExport: boolean;
  exportMessage: string;
  lastError?: string;
  lastSuccessAt?: string;
  nextAttemptAt?: string;
  reauthorize: boolean;
}
/**
 * ImportRule is one per-sport import switch.
 */
export interface ImportRule {
  connectionKind: string;
  sport: string;
  enabled: boolean;
}
/**
 * SyncRun summarises one sync pass.
 */
export interface SyncRun {
  connectionKind: string;
  startedAt: string;
  finishedAt?: string;
  imported: number /* int64 */;
  skipped: number /* int64 */;
  error?: string;
}
/**
 * ConnectionsResponse is the connections settings payload.
 */
export interface ConnectionsResponse {
  connections: Connection[];
  importRules: ImportRule[];
  lastRuns: SyncRun[];
}
/**
 * ExportState reports the export queue state of one activity.
 */
export interface ExportState {
  target: string;
  status: string;
  lastError?: string;
  updatedAt: string;
}
/**
 * PrivacyZone is one circular privacy zone.
 */
export interface PrivacyZone {
  id: number /* int64 */;
  label: string;
  lat: number /* float64 */;
  lon: number /* float64 */;
  radiusM: number /* int64 */;
}
/**
 * APIKey is one developer key, never carrying the secret.
 */
export interface APIKey {
  id: number /* int64 */;
  name: string;
  prefix: string;
  createdAt: string;
  lastUsedAt?: string;
}
/**
 * DeveloperMe is the identity a developer key resolves to.
 */
export interface DeveloperMe {
  id: number /* int64 */;
  username: string;
  email: string;
  displayName: string;
  createdAt: string;
}
/**
 * DeveloperPoint is one stored sample of the raw stream.
 */
export interface DeveloperPoint {
  seq: number /* int64 */;
  t: string;
  elapsedS: number /* int64 */;
  lat?: number /* float64 */;
  lon?: number /* float64 */;
  elevationM?: number /* float64 */;
  heartRate?: number /* int64 */;
  cadence?: number /* int64 */;
  powerW?: number /* int64 */;
  speedMps?: number /* float64 */;
  distanceM?: number /* float64 */;
}
/**
 * DeveloperActivity is the activity payload of the developer API: the summary
 * plus the full stored point stream and its provenance.
 */
export interface DeveloperActivity extends ActivitySummary {
  source: string;
  sourceRef?: string;
  points: DeveloperPoint[];
}
/**
 * APIKeyCreated is the one-time key reveal payload.
 */
export interface APIKeyCreated extends APIKey {
  key: string;
}
