// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"
	"strings"
)

const countActivities = `-- name: CountActivities :one
SELECT COUNT(*) AS total
FROM activities a
JOIN users u ON u.id = a.user_id
WHERE (CAST(?1 AS INTEGER) = 0 OR a.user_id = CAST(?1 AS INTEGER))
  AND (CAST(?2 AS INTEGER) = 0 OR a.user_id = ?3)
  AND (CAST(?4 AS INTEGER) = 0
       OR a.user_id = ?3
       OR a.user_id IN (SELECT f.followee_id FROM follows f
                        WHERE f.follower_id = ?3 AND f.status = 'accepted'))
  AND (CAST(?5 AS TEXT) = '' OR a.sport = CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) = ''
       OR a.title LIKE '%' || CAST(?6 AS TEXT) || '%'
       OR a.description LIKE '%' || CAST(?6 AS TEXT) || '%')
  AND (a.user_id = ?3
       OR (CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
             WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'everyone'
       OR ((CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
              WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'followers'
           AND EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?3
                       AND f2.followee_id = a.user_id AND f2.status = 'accepted')))
`

// CountActivities counts exactly the rows ListActivities can return for the same
// arguments, with no LIMIT/OFFSET. Its WHERE clause is the visibility twin of
// social.VisibilityAllows, identical to ListActivities above, and the two must
// stay in step so a page's total matches its rows.
func (q *Queries) CountActivities(ctx context.Context, ownerID int64, feedMe int64, viewerID int64, followingOnly int64, sportFilter string, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivities,
		ownerID,
		feedMe,
		viewerID,
		followingOnly,
		sportFilter,
		search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUserActivities = `-- name: CountUserActivities :one
SELECT COUNT(*) FROM activities WHERE user_id = ?
`

func (q *Queries) CountUserActivities(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActivities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s,
    distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps,
    avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w,
    has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s, distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps, avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w, has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at
`

type CreateActivityParams struct {
	UserID         int64
	Title          string
	Description    string
	Sport          string
	StartedAt      int64
	ElapsedTimeS   int64
	MovingTimeS    int64
	DistanceM      float64
	ElevationGainM float64
	ElevationLossM float64
	AvgSpeedMps    *float64
	MaxSpeedMps    *float64
	AvgHeartRate   *int64
	MaxHeartRate   *int64
	AvgCadence     *float64
	MaxCadence     *int64
	AvgPowerW      *float64
	MaxPowerW      *int64
	HasGps         bool
	RouteHidden    bool
	Visibility     string
	Source         string
	SourceRef      *string
	DedupeHash     string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Sport,
		arg.StartedAt,
		arg.ElapsedTimeS,
		arg.MovingTimeS,
		arg.DistanceM,
		arg.ElevationGainM,
		arg.ElevationLossM,
		arg.AvgSpeedMps,
		arg.MaxSpeedMps,
		arg.AvgHeartRate,
		arg.MaxHeartRate,
		arg.AvgCadence,
		arg.MaxCadence,
		arg.AvgPowerW,
		arg.MaxPowerW,
		arg.HasGps,
		arg.RouteHidden,
		arg.Visibility,
		arg.Source,
		arg.SourceRef,
		arg.DedupeHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Sport,
		&i.StartedAt,
		&i.ElapsedTimeS,
		&i.MovingTimeS,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ElevationLossM,
		&i.AvgSpeedMps,
		&i.MaxSpeedMps,
		&i.AvgHeartRate,
		&i.MaxHeartRate,
		&i.AvgCadence,
		&i.MaxCadence,
		&i.AvgPowerW,
		&i.MaxPowerW,
		&i.HasGps,
		&i.RouteHidden,
		&i.Visibility,
		&i.Source,
		&i.SourceRef,
		&i.DedupeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTombstone = `-- name: CreateTombstone :exec
INSERT INTO activity_tombstones (user_id, dedupe_hash, deleted_at)
VALUES (?, ?, ?)
ON CONFLICT (user_id, dedupe_hash) DO UPDATE SET deleted_at = excluded.deleted_at
`

func (q *Queries) CreateTombstone(ctx context.Context, userID int64, dedupeHash string, deletedAt int64) error {
	_, err := q.db.ExecContext(ctx, createTombstone, userID, dedupeHash, deletedAt)
	return err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities WHERE id = ?
`

func (q *Queries) DeleteActivity(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActivity = `-- name: GetActivity :one
SELECT id, user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s, distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps, avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w, has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at FROM activities WHERE id = ?
`

func (q *Queries) GetActivity(ctx context.Context, id int64) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Sport,
		&i.StartedAt,
		&i.ElapsedTimeS,
		&i.MovingTimeS,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ElevationLossM,
		&i.AvgSpeedMps,
		&i.MaxSpeedMps,
		&i.AvgHeartRate,
		&i.MaxHeartRate,
		&i.AvgCadence,
		&i.MaxCadence,
		&i.AvgPowerW,
		&i.MaxPowerW,
		&i.HasGps,
		&i.RouteHidden,
		&i.Visibility,
		&i.Source,
		&i.SourceRef,
		&i.DedupeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityByDedupe = `-- name: GetActivityByDedupe :one
SELECT id, user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s, distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps, avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w, has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at FROM activities WHERE user_id = ? AND dedupe_hash = ?
`

func (q *Queries) GetActivityByDedupe(ctx context.Context, userID int64, dedupeHash string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivityByDedupe, userID, dedupeHash)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Sport,
		&i.StartedAt,
		&i.ElapsedTimeS,
		&i.MovingTimeS,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ElevationLossM,
		&i.AvgSpeedMps,
		&i.MaxSpeedMps,
		&i.AvgHeartRate,
		&i.MaxHeartRate,
		&i.AvgCadence,
		&i.MaxCadence,
		&i.AvgPowerW,
		&i.MaxPowerW,
		&i.HasGps,
		&i.RouteHidden,
		&i.Visibility,
		&i.Source,
		&i.SourceRef,
		&i.DedupeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityBySourceRef = `-- name: GetActivityBySourceRef :one
SELECT id, user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s, distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps, avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w, has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at FROM activities WHERE user_id = ? AND source = ? AND source_ref = ?
`

func (q *Queries) GetActivityBySourceRef(ctx context.Context, userID int64, source string, sourceRef *string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivityBySourceRef, userID, source, sourceRef)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Sport,
		&i.StartedAt,
		&i.ElapsedTimeS,
		&i.MovingTimeS,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ElevationLossM,
		&i.AvgSpeedMps,
		&i.MaxSpeedMps,
		&i.AvgHeartRate,
		&i.MaxHeartRate,
		&i.AvgCadence,
		&i.MaxCadence,
		&i.AvgPowerW,
		&i.MaxPowerW,
		&i.HasGps,
		&i.RouteHidden,
		&i.Visibility,
		&i.Source,
		&i.SourceRef,
		&i.DedupeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityTotalsBySport = `-- name: GetActivityTotalsBySport :many
SELECT a.sport,
       COUNT(*) AS activity_count,
       CAST(COALESCE(SUM(a.distance_m), 0) AS REAL) AS distance_m,
       CAST(COALESCE(SUM(a.elevation_gain_m), 0) AS REAL) AS elevation_gain_m,
       CAST(COALESCE(SUM(a.moving_time_s), 0) AS INTEGER) AS moving_time_s,
       CAST(COALESCE(SUM(a.elapsed_time_s), 0) AS INTEGER) AS elapsed_time_s
FROM activities a
JOIN users u ON u.id = a.user_id
WHERE a.user_id = ?1
  AND (CAST(?2 AS INTEGER) = 0 OR a.started_at >= CAST(?2 AS INTEGER))
  AND (CAST(?3 AS INTEGER) = 0 OR a.started_at < CAST(?3 AS INTEGER))
  AND (a.user_id = ?4
       OR (CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
             WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'everyone'
       OR ((CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
              WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'followers'
           AND EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?4
                       AND f2.followee_id = a.user_id AND f2.status = 'accepted')))
GROUP BY a.sport
ORDER BY a.sport
`

type GetActivityTotalsBySportRow struct {
	Sport          string
	ActivityCount  int64
	DistanceM      float64
	ElevationGainM float64
	MovingTimeS    int64
	ElapsedTimeS   int64
}

// Same visibility predicate as ListActivities above.
func (q *Queries) GetActivityTotalsBySport(ctx context.Context, ownerID int64, fromTs int64, toTs int64, viewerID int64) ([]GetActivityTotalsBySportRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivityTotalsBySport,
		ownerID,
		fromTs,
		toTs,
		viewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivityTotalsBySportRow{}
	for rows.Next() {
		var i GetActivityTotalsBySportRow
		if err := rows.Scan(
			&i.Sport,
			&i.ActivityCount,
			&i.DistanceM,
			&i.ElevationGainM,
			&i.MovingTimeS,
			&i.ElapsedTimeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTombstone = `-- name: GetTombstone :one
SELECT user_id, dedupe_hash, deleted_at FROM activity_tombstones WHERE user_id = ? AND dedupe_hash = ?
`

func (q *Queries) GetTombstone(ctx context.Context, userID int64, dedupeHash string) (ActivityTombstone, error) {
	row := q.db.QueryRowContext(ctx, getTombstone, userID, dedupeHash)
	var i ActivityTombstone
	err := row.Scan(&i.UserID, &i.DedupeHash, &i.DeletedAt)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT a.id, a.user_id, u.username, u.display_name, a.title, a.description, a.sport, a.started_at,
       a.distance_m, a.moving_time_s, a.elapsed_time_s, a.elevation_gain_m,
       a.avg_speed_mps, a.max_speed_mps, a.avg_heart_rate, a.max_heart_rate,
       a.avg_cadence, a.avg_power_w, a.has_gps, a.route_hidden, a.visibility,
       u.trim_scope, u.trim_radius_m,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = u.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS avatar_media_id,
       (SELECT COUNT(*) FROM likes l WHERE l.activity_id = a.id) AS like_count,
       (SELECT COUNT(*) FROM comments c WHERE c.activity_id = a.id AND c.deleted_at IS NULL) AS comment_count,
       EXISTS (SELECT 1 FROM likes l2 WHERE l2.activity_id = a.id AND l2.user_id = ?1) AS liked_by_me,
       (SELECT COUNT(*) FROM media m2 WHERE m2.activity_id = a.id AND m2.deleted_at IS NULL) AS photo_count
FROM activities a
JOIN users u ON u.id = a.user_id
WHERE (CAST(?2 AS INTEGER) = 0 OR a.user_id = CAST(?2 AS INTEGER))
  AND (CAST(?3 AS INTEGER) = 0 OR a.user_id = ?1)
  AND (CAST(?4 AS INTEGER) = 0
       OR a.user_id = ?1
       OR a.user_id IN (SELECT f.followee_id FROM follows f
                        WHERE f.follower_id = ?1 AND f.status = 'accepted'))
  AND (CAST(?5 AS TEXT) = '' OR a.sport = CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) = ''
       OR a.title LIKE '%' || CAST(?6 AS TEXT) || '%'
       OR a.description LIKE '%' || CAST(?6 AS TEXT) || '%')
  AND (a.user_id = ?1
       OR (CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
             WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'everyone'
       OR ((CASE a.visibility WHEN 'everyone' THEN 'everyone' WHEN 'followers' THEN 'followers'
              WHEN 'only_me' THEN 'only_me' ELSE u.activities_visibility END) = 'followers'
           AND EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?1
                       AND f2.followee_id = a.user_id AND f2.status = 'accepted')))
ORDER BY a.started_at DESC, a.id DESC
LIMIT ?8 OFFSET ?7
`

type ListActivitiesParams struct {
	ViewerID      int64
	OwnerID       int64
	FeedMe        int64
	FollowingOnly int64
	SportFilter   string
	Search        string
	OffsetCount   int64
	LimitCount    int64
}

type ListActivitiesRow struct {
	ID             int64
	UserID         int64
	Username       string
	DisplayName    string
	Title          string
	Description    string
	Sport          string
	StartedAt      int64
	DistanceM      float64
	MovingTimeS    int64
	ElapsedTimeS   int64
	ElevationGainM float64
	AvgSpeedMps    *float64
	MaxSpeedMps    *float64
	AvgHeartRate   *int64
	MaxHeartRate   *int64
	AvgCadence     *float64
	AvgPowerW      *float64
	HasGps         bool
	RouteHidden    bool
	Visibility     string
	TrimScope      string
	TrimRadiusM    int64
	AvatarMediaID  int64
	LikeCount      int64
	CommentCount   int64
	LikedByMe      bool
	PhotoCount     int64
}

// The CASE expression below is the SQL twin of social.VisibilityAllows: it
// resolves an activity's `default` visibility to its owner's
// activities_visibility, then decides whether the viewer is allowed. The two
// must keep agreeing, which TestVisibilityAgreesWithSQL asserts. CountActivities
// repeats this predicate verbatim and must stay in step with it too, or a
// page's total would disagree with the rows the list can return.
//
// One query serves every activity list:
//
//	home feed        owner_id = 0, feed_me = 0, following_only = 1
//	feed=me          owner_id = 0, feed_me = 1, following_only = 0
//	a profile page   owner_id = <profile>, feed_me = 0, following_only = 0
//
// Rows are ordered by when the activity happened (started_at DESC, id DESC for
// the tiebreak), not by insertion order, so a late import (intervals sync) does
// not jump to the top of the feed. Activity lists are page-numbered: the
// handler turns ?page= into LIMIT/OFFSET and pairs it with the CountActivities
// total, so page N always holds the same rows because the sort order is total.
//
// search = ” disables the text filter; otherwise it matches title or
// description with a case-insensitive LIKE. It is applied after the visibility
// predicate and can never widen what the viewer may see.
func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivities,
		arg.ViewerID,
		arg.OwnerID,
		arg.FeedMe,
		arg.FollowingOnly,
		arg.SportFilter,
		arg.Search,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesRow{}
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Title,
			&i.Description,
			&i.Sport,
			&i.StartedAt,
			&i.DistanceM,
			&i.MovingTimeS,
			&i.ElapsedTimeS,
			&i.ElevationGainM,
			&i.AvgSpeedMps,
			&i.MaxSpeedMps,
			&i.AvgHeartRate,
			&i.MaxHeartRate,
			&i.AvgCadence,
			&i.AvgPowerW,
			&i.HasGps,
			&i.RouteHidden,
			&i.Visibility,
			&i.TrimScope,
			&i.TrimRadiusM,
			&i.AvatarMediaID,
			&i.LikeCount,
			&i.CommentCount,
			&i.LikedByMe,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityPoints = `-- name: ListActivityPoints :many
SELECT activity_id, seq, t, elapsed_s, lat, lon, ele, hr, cad, pwr, spd, dist_m FROM activity_points WHERE activity_id = ? ORDER BY seq
`

func (q *Queries) ListActivityPoints(ctx context.Context, activityID int64) ([]ActivityPoint, error) {
	rows, err := q.db.QueryContext(ctx, listActivityPoints, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityPoint{}
	for rows.Next() {
		var i ActivityPoint
		if err := rows.Scan(
			&i.ActivityID,
			&i.Seq,
			&i.T,
			&i.ElapsedS,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Hr,
			&i.Cad,
			&i.Pwr,
			&i.Spd,
			&i.DistM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointsForActivities = `-- name: ListPointsForActivities :many
SELECT activity_id, seq, t, elapsed_s, lat, lon, ele, hr, cad, pwr, spd, dist_m FROM activity_points
WHERE activity_id IN (/*SLICE:activity_ids*/?)
ORDER BY activity_id, seq
`

func (q *Queries) ListPointsForActivities(ctx context.Context, activityIds []int64) ([]ActivityPoint, error) {
	query := listPointsForActivities
	var queryParams []interface{}
	if len(activityIds) > 0 {
		for _, v := range activityIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:activity_ids*/?", strings.Repeat(",?", len(activityIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:activity_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityPoint{}
	for rows.Next() {
		var i ActivityPoint
		if err := rows.Scan(
			&i.ActivityID,
			&i.Seq,
			&i.T,
			&i.ElapsedS,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Hr,
			&i.Cad,
			&i.Pwr,
			&i.Spd,
			&i.DistM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET title = ?, description = ?, sport = ?, visibility = ?, route_hidden = ?, updated_at = ?
WHERE id = ?
RETURNING id, user_id, title, description, sport, started_at, elapsed_time_s, moving_time_s, distance_m, elevation_gain_m, elevation_loss_m, avg_speed_mps, max_speed_mps, avg_heart_rate, max_heart_rate, avg_cadence, max_cadence, avg_power_w, max_power_w, has_gps, route_hidden, visibility, source, source_ref, dedupe_hash, created_at, updated_at
`

type UpdateActivityParams struct {
	Title       string
	Description string
	Sport       string
	Visibility  string
	RouteHidden bool
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivity,
		arg.Title,
		arg.Description,
		arg.Sport,
		arg.Visibility,
		arg.RouteHidden,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Sport,
		&i.StartedAt,
		&i.ElapsedTimeS,
		&i.MovingTimeS,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ElevationLossM,
		&i.AvgSpeedMps,
		&i.MaxSpeedMps,
		&i.AvgHeartRate,
		&i.MaxHeartRate,
		&i.AvgCadence,
		&i.MaxCadence,
		&i.AvgPowerW,
		&i.MaxPowerW,
		&i.HasGps,
		&i.RouteHidden,
		&i.Visibility,
		&i.Source,
		&i.SourceRef,
		&i.DedupeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
