// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :execrows
UPDATE email_tokens SET consumed_at = ? WHERE id = ? AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailToken(ctx context.Context, consumedAt *int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEmailToken, consumedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countIdentitiesForUser = `-- name: CountIdentitiesForUser :one
SELECT COUNT(*) FROM auth_identities WHERE user_id = ?
`

func (q *Queries) CountIdentitiesForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIdentitiesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (user_id, kind, token_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

func (q *Queries) CreateEmailToken(ctx context.Context, userID int64, kind string, tokenHash []byte, expiresAt int64, createdAt int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEmailToken,
		userID,
		kind,
		tokenHash,
		expiresAt,
		createdAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_user_id, email, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, provider, provider_user_id, email, created_at
`

func (q *Queries) CreateIdentity(ctx context.Context, userID int64, provider string, providerUserID string, email *string, createdAt int64) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		userID,
		provider,
		providerUserID,
		email,
		createdAt,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, created_at, expires_at, user_agent, ip)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, token_hash, created_at, expires_at, user_agent, ip
`

func (q *Queries) CreateSession(ctx context.Context, userID int64, tokenHash []byte, createdAt int64, expiresAt int64, userAgent string, ip string) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		userID,
		tokenHash,
		createdAt,
		expiresAt,
		userAgent,
		ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM auth_identities WHERE user_id = ? AND provider = ?
`

func (q *Queries) DeleteIdentity(ctx context.Context, userID int64, provider string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIdentity, userID, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = ? AND token_hash <> ?
`

func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, userID int64, tokenHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOtherSessionsForUser, userID, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT id, user_id, kind, token_hash, expires_at, consumed_at, created_at FROM email_tokens WHERE token_hash = ? AND kind = ?
`

func (q *Queries) GetEmailToken(ctx context.Context, tokenHash []byte, kind string) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailToken, tokenHash, kind)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, user_id, provider, provider_user_id, email, created_at FROM auth_identities WHERE provider = ? AND provider_user_id = ?
`

func (q *Queries) GetIdentity(ctx context.Context, provider string, providerUserID string) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, provider, providerUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, user_agent, ip FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const invalidateEmailTokens = `-- name: InvalidateEmailTokens :execrows
UPDATE email_tokens SET consumed_at = ? WHERE user_id = ? AND kind = ? AND consumed_at IS NULL
`

func (q *Queries) InvalidateEmailTokens(ctx context.Context, consumedAt *int64, userID int64, kind string) (int64, error) {
	result, err := q.db.ExecContext(ctx, invalidateEmailTokens, consumedAt, userID, kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listIdentitiesForUser = `-- name: ListIdentitiesForUser :many
SELECT id, user_id, provider, provider_user_id, email, created_at FROM auth_identities WHERE user_id = ? ORDER BY provider
`

func (q *Queries) ListIdentitiesForUser(ctx context.Context, userID int64) ([]AuthIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :execrows
UPDATE sessions SET created_at = ?, expires_at = ? WHERE id = ?
`

func (q *Queries) UpdateSessionExpiry(ctx context.Context, createdAt int64, expiresAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionExpiry, createdAt, expiresAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
