// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"strings"
)

const countActivityMedia = `-- name: CountActivityMedia :one
SELECT COUNT(*) FROM media WHERE activity_id = CAST(?1 AS INTEGER) AND deleted_at IS NULL
`

func (q *Queries) CountActivityMedia(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityMedia, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (user_id, activity_id, kind, position, width, height, bytes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, activity_id, kind, position, width, height, bytes, created_at, deleted_at
`

type CreateMediaParams struct {
	UserID     int64
	ActivityID *int64
	Kind       string
	Position   int64
	Width      int64
	Height     int64
	Bytes      int64
	CreatedAt  int64
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.UserID,
		arg.ActivityID,
		arg.Kind,
		arg.Position,
		arg.Width,
		arg.Height,
		arg.Bytes,
		arg.CreatedAt,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Kind,
		&i.Position,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveAvatar = `-- name: GetActiveAvatar :one
SELECT id, user_id, activity_id, kind, position, width, height, bytes, created_at, deleted_at FROM media WHERE user_id = ? AND kind = 'avatar' AND deleted_at IS NULL
`

func (q *Queries) GetActiveAvatar(ctx context.Context, userID int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getActiveAvatar, userID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Kind,
		&i.Position,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, user_id, activity_id, kind, position, width, height, bytes, created_at, deleted_at FROM media WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Kind,
		&i.Position,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAvatarIDs = `-- name: ListActiveAvatarIDs :many
SELECT id, user_id FROM media
WHERE kind = 'avatar' AND deleted_at IS NULL AND user_id IN (/*SLICE:user_ids*/?)
`

type ListActiveAvatarIDsRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) ListActiveAvatarIDs(ctx context.Context, userIds []int64) ([]ListActiveAvatarIDsRow, error) {
	query := listActiveAvatarIDs
	var queryParams []interface{}
	if len(userIds) > 0 {
		for _, v := range userIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(userIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAvatarIDsRow{}
	for rows.Next() {
		var i ListActiveAvatarIDsRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityMedia = `-- name: ListActivityMedia :many
SELECT id, user_id, activity_id, kind, position, width, height, bytes, created_at, deleted_at FROM media
WHERE activity_id = CAST(?1 AS INTEGER) AND deleted_at IS NULL
ORDER BY position, id
`

func (q *Queries) ListActivityMedia(ctx context.Context, activityID int64) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listActivityMedia, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityID,
			&i.Kind,
			&i.Position,
			&i.Width,
			&i.Height,
			&i.Bytes,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMediaPosition = `-- name: NextMediaPosition :one
SELECT CAST(COALESCE(MAX(position), -1) + 1 AS INTEGER) AS next_position
FROM media WHERE activity_id = CAST(?1 AS INTEGER)
`

func (q *Queries) NextMediaPosition(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMediaPosition, activityID)
	var next_position int64
	err := row.Scan(&next_position)
	return next_position, err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :execrows
UPDATE media SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, deletedAt *int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteMedia, deletedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteUserAvatars = `-- name: SoftDeleteUserAvatars :execrows
UPDATE media SET deleted_at = ? WHERE user_id = ? AND kind = 'avatar' AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUserAvatars(ctx context.Context, deletedAt *int64, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteUserAvatars, deletedAt, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMediaSize = `-- name: UpdateMediaSize :execrows
UPDATE media SET width = ?, height = ?, bytes = ? WHERE id = ?
`

func (q *Queries) UpdateMediaSize(ctx context.Context, width int64, height int64, bytes int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMediaSize,
		width,
		height,
		bytes,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
