// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Activity struct {
	ID             int64
	UserID         int64
	Title          string
	Description    string
	Sport          string
	StartedAt      int64
	ElapsedTimeS   int64
	MovingTimeS    int64
	DistanceM      float64
	ElevationGainM float64
	ElevationLossM float64
	AvgSpeedMps    *float64
	MaxSpeedMps    *float64
	AvgHeartRate   *int64
	MaxHeartRate   *int64
	AvgCadence     *float64
	MaxCadence     *int64
	AvgPowerW      *float64
	MaxPowerW      *int64
	HasGps         bool
	RouteHidden    bool
	Visibility     string
	Source         string
	SourceRef      *string
	DedupeHash     string
	CreatedAt      int64
	UpdatedAt      int64
}

type ActivityExport struct {
	ID         int64
	ActivityID int64
	UserID     int64
	Target     string
	Status     string
	ExternalID string
	RemoteID   *string
	Attempts   int64
	LastError  *string
	CreatedAt  int64
	UpdatedAt  int64
}

type ActivityPoint struct {
	ActivityID int64
	Seq        int64
	T          int64
	ElapsedS   int64
	Lat        *float64
	Lon        *float64
	Ele        *float64
	Hr         *int64
	Cad        *int64
	Pwr        *int64
	Spd        *float64
	DistM      *float64
}

type ActivityTombstone struct {
	UserID     int64
	DedupeHash string
	DeletedAt  int64
}

type ApiKey struct {
	ID         int64
	UserID     int64
	Name       string
	KeyHash    []byte
	Prefix     string
	CreatedAt  int64
	LastUsedAt *int64
	RevokedAt  *int64
}

type AuthIdentity struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	Email          *string
	CreatedAt      int64
}

type Comment struct {
	ID         int64
	ActivityID int64
	UserID     int64
	Body       string
	CreatedAt  int64
	DeletedAt  *int64
}

type CommentMention struct {
	CommentID       int64
	MentionedUserID int64
}

type Connection struct {
	ID                 int64
	UserID             int64
	Kind               string
	ExternalAthleteID  *string
	AccessTokenCipher  []byte
	RefreshTokenCipher []byte
	TokenExpiresAt     *int64
	AutoExport         bool
	ExportMessage      string
	SyncedFrom         *int64
	LastSuccessAt      *int64
	LastError          *string
	NextAttemptAt      *int64
	CreatedAt          int64
	UpdatedAt          int64
}

type EmailToken struct {
	ID         int64
	UserID     int64
	Kind       string
	TokenHash  []byte
	ExpiresAt  int64
	ConsumedAt *int64
	CreatedAt  int64
}

type Follow struct {
	FollowerID  int64
	FolloweeID  int64
	Status      string
	CreatedAt   int64
	RespondedAt *int64
}

type ImportRule struct {
	ID             int64
	UserID         int64
	ConnectionKind string
	Sport          string
	Enabled        bool
	UpdatedAt      int64
}

type Like struct {
	ActivityID int64
	UserID     int64
	CreatedAt  int64
}

type Medium struct {
	ID         int64
	UserID     int64
	ActivityID *int64
	Kind       string
	Position   int64
	Width      int64
	Height     int64
	Bytes      int64
	CreatedAt  int64
	DeletedAt  *int64
}

type Notification struct {
	ID         int64
	UserID     int64
	ActorID    int64
	Kind       string
	ActivityID *int64
	CommentID  *int64
	CreatedAt  int64
	ReadAt     *int64
}

type PrivacyZone struct {
	ID        int64
	UserID    int64
	Label     string
	Lat       float64
	Lon       float64
	RadiusM   int64
	CreatedAt int64
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	CreatedAt int64
	ExpiresAt int64
	UserAgent string
	Ip        string
}

type SyncRun struct {
	ID             int64
	UserID         int64
	ConnectionKind string
	StartedAt      int64
	FinishedAt     *int64
	Imported       int64
	Skipped        int64
	Error          *string
}

type User struct {
	ID                   int64
	Username             string
	Email                string
	DisplayName          string
	Bio                  string
	PasswordHash         *string
	EmailVerified        bool
	IsAdmin              bool
	ProfileVisibility    string
	ActivitiesVisibility string
	FollowPolicy         string
	MentionPolicy        string
	TrimScope            string
	TrimRadiusM          int64
	CreatedAt            int64
	UpdatedAt            int64
}
