// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy_keys.sql

package db

import (
	"context"
)

const countPrivacyZones = `-- name: CountPrivacyZones :one
SELECT COUNT(*) FROM privacy_zones WHERE user_id = ?
`

func (q *Queries) CountPrivacyZones(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrivacyZones, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, prefix, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, key_hash, prefix, created_at, last_used_at, revoked_at
`

func (q *Queries) CreateAPIKey(ctx context.Context, userID int64, name string, keyHash []byte, prefix string, createdAt int64) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		userID,
		name,
		keyHash,
		prefix,
		createdAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createPrivacyZone = `-- name: CreatePrivacyZone :one
INSERT INTO privacy_zones (user_id, label, lat, lon, radius_m, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, label, lat, lon, radius_m, created_at
`

func (q *Queries) CreatePrivacyZone(ctx context.Context, userID int64, label string, lat float64, lon float64, radiusM int64, createdAt int64) (PrivacyZone, error) {
	row := q.db.QueryRowContext(ctx, createPrivacyZone,
		userID,
		label,
		lat,
		lon,
		radiusM,
		createdAt,
	)
	var i PrivacyZone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Lat,
		&i.Lon,
		&i.RadiusM,
		&i.CreatedAt,
	)
	return i, err
}

const deletePrivacyZone = `-- name: DeletePrivacyZone :execrows
DELETE FROM privacy_zones WHERE id = ? AND user_id = ?
`

func (q *Queries) DeletePrivacyZone(ctx context.Context, iD int64, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrivacyZone, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, prefix, created_at, last_used_at, revoked_at FROM api_keys WHERE key_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, key_hash, prefix, created_at, last_used_at, revoked_at FROM api_keys WHERE user_id = ? AND revoked_at IS NULL ORDER BY id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacyZones = `-- name: ListPrivacyZones :many
SELECT id, user_id, label, lat, lon, radius_m, created_at FROM privacy_zones WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListPrivacyZones(ctx context.Context, userID int64) ([]PrivacyZone, error) {
	rows, err := q.db.QueryContext(ctx, listPrivacyZones, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrivacyZone{}
	for rows.Next() {
		var i PrivacyZone
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Lat,
			&i.Lon,
			&i.RadiusM,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE id = ? AND user_id = ?
`

func (q *Queries) RevokeAPIKey(ctx context.Context, revokedAt *int64, iD int64, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, revokedAt, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

func (q *Queries) TouchAPIKey(ctx context.Context, lastUsedAt *int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, lastUsedAt, iD)
	return err
}
