// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"
	"strings"
)

const acceptFollow = `-- name: AcceptFollow :execrows
UPDATE follows SET status = 'accepted', responded_at = ?
WHERE follower_id = ? AND followee_id = ? AND status = 'pending'
`

func (q *Queries) AcceptFollow(ctx context.Context, respondedAt *int64, followerID int64, followeeID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptFollow, respondedAt, followerID, followeeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countComments = `-- name: CountComments :one
SELECT COUNT(*) FROM comments WHERE activity_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountComments(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComments, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE followee_id = ? AND status = 'accepted'
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = ? AND status = 'accepted'
`

func (q *Queries) CountFollowing(ctx context.Context, followerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikes = `-- name: CountLikes :one
SELECT COUNT(*) FROM likes WHERE activity_id = ?
`

func (q *Queries) CountLikes(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikes, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (activity_id, user_id, body, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, activity_id, user_id, body, created_at, deleted_at
`

func (q *Queries) CreateComment(ctx context.Context, activityID int64, userID int64, body string, createdAt int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		activityID,
		userID,
		body,
		createdAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMention = `-- name: CreateMention :exec
INSERT INTO comment_mentions (comment_id, mentioned_user_id)
VALUES (?, ?)
ON CONFLICT (comment_id, mentioned_user_id) DO NOTHING
`

func (q *Queries) CreateMention(ctx context.Context, commentID int64, mentionedUserID int64) error {
	_, err := q.db.ExecContext(ctx, createMention, commentID, mentionedUserID)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, actor_id, kind, activity_id, comment_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, actor_id, kind, activity_id, comment_id, created_at, read_at
`

func (q *Queries) CreateNotification(ctx context.Context, userID int64, actorID int64, kind string, activityID *int64, commentID *int64, createdAt int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		userID,
		actorID,
		kind,
		activityID,
		commentID,
		createdAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.Kind,
		&i.ActivityID,
		&i.CommentID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :execrows
DELETE FROM follows WHERE follower_id = ? AND followee_id = ?
`

func (q *Queries) DeleteFollow(ctx context.Context, followerID int64, followeeID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFollow, followerID, followeeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComment = `-- name: GetComment :one
SELECT id, activity_id, user_id, body, created_at, deleted_at FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFollow = `-- name: GetFollow :one
SELECT follower_id, followee_id, status, created_at, responded_at FROM follows WHERE follower_id = ? AND followee_id = ?
`

func (q *Queries) GetFollow(ctx context.Context, followerID int64, followeeID int64) (Follow, error) {
	row := q.db.QueryRowContext(ctx, getFollow, followerID, followeeID)
	var i Follow
	err := row.Scan(
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getLike = `-- name: GetLike :one
SELECT activity_id, user_id, created_at FROM likes WHERE activity_id = ? AND user_id = ?
`

func (q *Queries) GetLike(ctx context.Context, activityID int64, userID int64) (Like, error) {
	row := q.db.QueryRowContext(ctx, getLike, activityID, userID)
	var i Like
	err := row.Scan(&i.ActivityID, &i.UserID, &i.CreatedAt)
	return i, err
}

const insertLike = `-- name: InsertLike :exec
INSERT INTO likes (activity_id, user_id, created_at)
VALUES (?, ?, ?)
ON CONFLICT (activity_id, user_id) DO NOTHING
`

func (q *Queries) InsertLike(ctx context.Context, activityID int64, userID int64, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, insertLike, activityID, userID, createdAt)
	return err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.activity_id, c.user_id, c.body, c.created_at,
       u.username, u.display_name,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = u.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS avatar_media_id
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.activity_id = ?1 AND c.deleted_at IS NULL
  AND (CAST(?2 AS INTEGER) = 0 OR c.id < CAST(?2 AS INTEGER))
ORDER BY c.id DESC
LIMIT ?3
`

type ListCommentsRow struct {
	ID            int64
	ActivityID    int64
	UserID        int64
	Body          string
	CreatedAt     int64
	Username      string
	DisplayName   string
	AvatarMediaID int64
}

func (q *Queries) ListComments(ctx context.Context, activityID int64, beforeID int64, limitCount int64) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments, activityID, beforeID, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.display_name, u.bio,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = u.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS avatar_media_id,
       EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?1
               AND f2.followee_id = u.id AND f2.status = 'accepted') AS is_following,
       EXISTS (SELECT 1 FROM follows f3 WHERE f3.follower_id = u.id
               AND f3.followee_id = ?1 AND f3.status = 'pending') AS incoming_pending,
       EXISTS (SELECT 1 FROM follows f4 WHERE f4.follower_id = ?1
               AND f4.followee_id = u.id AND f4.status = 'pending') AS outgoing_pending
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = ?1 AND f.status = 'accepted'
ORDER BY u.username
LIMIT ?2
`

type ListFollowersRow struct {
	ID              int64
	Username        string
	DisplayName     string
	Bio             string
	AvatarMediaID   int64
	IsFollowing     bool
	IncomingPending bool
	OutgoingPending bool
}

func (q *Queries) ListFollowers(ctx context.Context, viewerID int64, limitCount int64) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, viewerID, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarMediaID,
			&i.IsFollowing,
			&i.IncomingPending,
			&i.OutgoingPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.display_name, u.bio,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = u.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS avatar_media_id,
       EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?1
               AND f2.followee_id = u.id AND f2.status = 'accepted') AS is_following,
       EXISTS (SELECT 1 FROM follows f3 WHERE f3.follower_id = u.id
               AND f3.followee_id = ?1 AND f3.status = 'pending') AS incoming_pending,
       EXISTS (SELECT 1 FROM follows f4 WHERE f4.follower_id = ?1
               AND f4.followee_id = u.id AND f4.status = 'pending') AS outgoing_pending
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = ?1 AND f.status = 'accepted'
ORDER BY u.username
LIMIT ?2
`

type ListFollowingRow struct {
	ID              int64
	Username        string
	DisplayName     string
	Bio             string
	AvatarMediaID   int64
	IsFollowing     bool
	IncomingPending bool
	OutgoingPending bool
}

func (q *Queries) ListFollowing(ctx context.Context, viewerID int64, limitCount int64) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, viewerID, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarMediaID,
			&i.IsFollowing,
			&i.IncomingPending,
			&i.OutgoingPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionedUsers = `-- name: ListMentionedUsers :many
SELECT u.username
FROM comment_mentions cm
JOIN users u ON u.id = cm.mentioned_user_id
WHERE cm.comment_id = ?
ORDER BY u.username
`

func (q *Queries) ListMentionedUsers(ctx context.Context, commentID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMentionedUsers, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsForComments = `-- name: ListMentionsForComments :many
SELECT cm.comment_id, u.username
FROM comment_mentions cm
JOIN users u ON u.id = cm.mentioned_user_id
WHERE cm.comment_id IN (/*SLICE:comment_ids*/?)
ORDER BY cm.comment_id, u.username
`

type ListMentionsForCommentsRow struct {
	CommentID int64
	Username  string
}

func (q *Queries) ListMentionsForComments(ctx context.Context, commentIds []int64) ([]ListMentionsForCommentsRow, error) {
	query := listMentionsForComments
	var queryParams []interface{}
	if len(commentIds) > 0 {
		for _, v := range commentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:comment_ids*/?", strings.Repeat(",?", len(commentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:comment_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionsForCommentsRow{}
	for rows.Next() {
		var i ListMentionsForCommentsRow
		if err := rows.Scan(&i.CommentID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.kind, n.activity_id, n.comment_id, n.created_at, n.read_at,
       a.username AS actor_username, a.display_name AS actor_display_name,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = a.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS actor_avatar_media_id
FROM notifications n
JOIN users a ON a.id = n.actor_id
WHERE n.user_id = ?1
  AND (CAST(?2 AS INTEGER) = 0 OR n.id < CAST(?2 AS INTEGER))
ORDER BY n.id DESC
LIMIT ?3
`

type ListNotificationsRow struct {
	ID                 int64
	Kind               string
	ActivityID         *int64
	CommentID          *int64
	CreatedAt          int64
	ReadAt             *int64
	ActorUsername      string
	ActorDisplayName   string
	ActorAvatarMediaID int64
}

func (q *Queries) ListNotifications(ctx context.Context, userID int64, beforeID int64, limitCount int64) ([]ListNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, userID, beforeID, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ActivityID,
			&i.CommentID,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ActorUsername,
			&i.ActorDisplayName,
			&i.ActorAvatarMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFollowRequests = `-- name: ListPendingFollowRequests :many
SELECT u.id, u.username, u.display_name, u.bio,
       CAST(COALESCE((SELECT m.id FROM media m WHERE m.user_id = u.id AND m.kind = 'avatar'
                 AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 1), 0) AS INTEGER) AS avatar_media_id,
       EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = ?1
               AND f2.followee_id = u.id AND f2.status = 'accepted') AS is_following,
       EXISTS (SELECT 1 FROM follows f3 WHERE f3.follower_id = u.id
               AND f3.followee_id = ?1 AND f3.status = 'pending') AS incoming_pending,
       EXISTS (SELECT 1 FROM follows f4 WHERE f4.follower_id = ?1
               AND f4.followee_id = u.id AND f4.status = 'pending') AS outgoing_pending
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = ?1 AND f.status = 'pending'
ORDER BY f.created_at DESC
LIMIT ?2
`

type ListPendingFollowRequestsRow struct {
	ID              int64
	Username        string
	DisplayName     string
	Bio             string
	AvatarMediaID   int64
	IsFollowing     bool
	IncomingPending bool
	OutgoingPending bool
}

func (q *Queries) ListPendingFollowRequests(ctx context.Context, viewerID int64, limitCount int64) ([]ListPendingFollowRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingFollowRequests, viewerID, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingFollowRequestsRow{}
	for rows.Next() {
		var i ListPendingFollowRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarMediaID,
			&i.IsFollowing,
			&i.IncomingPending,
			&i.OutgoingPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, readAt *int64, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsRead, readAt, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = ? WHERE id = ? AND user_id = ? AND read_at IS NULL
`

func (q *Queries) MarkNotificationRead(ctx context.Context, readAt *int64, iD int64, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, readAt, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, deletedAt *int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteComment, deletedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertFollow = `-- name: UpsertFollow :exec
INSERT INTO follows (follower_id, followee_id, status, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (follower_id, followee_id) DO UPDATE
    SET status = excluded.status, created_at = excluded.created_at, responded_at = NULL
    WHERE follows.status <> 'accepted'
`

func (q *Queries) UpsertFollow(ctx context.Context, followerID int64, followeeID int64, status string, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, upsertFollow,
		followerID,
		followeeID,
		status,
		createdAt,
	)
	return err
}
