// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, display_name, bio, password_hash, email_verified, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at
`

type CreateUserParams struct {
	Username      string
	Email         string
	DisplayName   string
	Bio           string
	PasswordHash  *string
	EmailVerified bool
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Bio,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailTaken = `-- name: EmailTaken :one
SELECT COUNT(*) FROM users WHERE email = ?
`

func (q *Queries) EmailTaken(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, emailTaken, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users SET email_verified = 1, updated_at = ? WHERE id = ?
`

func (q *Queries) MarkEmailVerified(ctx context.Context, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerified, updatedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at FROM users
WHERE username LIKE CAST(?1 AS TEXT) || '%' OR display_name LIKE CAST(?1 AS TEXT) || '%'
ORDER BY username
LIMIT ?2
`

func (q *Queries) SearchUsers(ctx context.Context, query string, limitCount int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, query, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.Bio,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.ProfileVisibility,
			&i.ActivitiesVisibility,
			&i.FollowPolicy,
			&i.MentionPolicy,
			&i.TrimScope,
			&i.TrimRadiusM,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users SET email = ?, email_verified = ?, updated_at = ? WHERE id = ?
`

func (q *Queries) UpdateUserEmail(ctx context.Context, email string, emailVerified bool, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserEmail,
		email,
		emailVerified,
		updatedAt,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

func (q *Queries) UpdateUserPassword(ctx context.Context, passwordHash *string, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, passwordHash, updatedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPrivacy = `-- name: UpdateUserPrivacy :one
UPDATE users
SET profile_visibility = ?, activities_visibility = ?, follow_policy = ?, mention_policy = ?,
    trim_scope = ?, trim_radius_m = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at
`

type UpdateUserPrivacyParams struct {
	ProfileVisibility    string
	ActivitiesVisibility string
	FollowPolicy         string
	MentionPolicy        string
	TrimScope            string
	TrimRadiusM          int64
	UpdatedAt            int64
	ID                   int64
}

func (q *Queries) UpdateUserPrivacy(ctx context.Context, arg UpdateUserPrivacyParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPrivacy,
		arg.ProfileVisibility,
		arg.ActivitiesVisibility,
		arg.FollowPolicy,
		arg.MentionPolicy,
		arg.TrimScope,
		arg.TrimRadiusM,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = ?, bio = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, email, display_name, bio, password_hash, email_verified, profile_visibility, activities_visibility, follow_policy, mention_policy, trim_scope, trim_radius_m, created_at, updated_at
`

func (q *Queries) UpdateUserProfile(ctx context.Context, displayName string, bio string, updatedAt int64, iD int64) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		displayName,
		bio,
		updatedAt,
		iD,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ProfileVisibility,
		&i.ActivitiesVisibility,
		&i.FollowPolicy,
		&i.MentionPolicy,
		&i.TrimScope,
		&i.TrimRadiusM,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usernameTaken = `-- name: UsernameTaken :one
SELECT COUNT(*) FROM users WHERE username = ?
`

func (q *Queries) UsernameTaken(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, usernameTaken, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}
